name: Deploy HTML5 to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Iniciar sesión en Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_322615E7DEC345B591629FEF1DB8062B }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_C707BBFDE42F4180AFC16B7138AC25A7 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_3709023DCF8F418F95BC39831C29E6EF }}

      - name: Desplegar página en Azure
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'sistema-calificaciones'
          slot-name: 'Production'
          package: ./public_html
